# Lando config file.
# Uses Pantheon recipe: https://docs.lando.dev/pantheon/getting-started.html
name: atdove-d7
recipe: pantheon
config:
  framework: drupal
  site: atdove-d7
  id: d2e44185-85d8-4ffa-a0b3-a8c4078abda8
  api_version: 1
  database: pantheon
  username: pantheon
  password: pantheon
  host: database
  port: 3306
  # Set Xdebug to off by default. Enable it with lando xdebug.
  xdebug: false
  # Disable Solr.
  index: false
  # Enable Redis.
  cache: true
  config:
    php: lando/php-conf/php.ini
proxy:
  appserver_nginx:
    # Add reliable domain. Requires adding to /etc/hosts on local machine to work.
    - atdove-d7.lando
services:
  appserver:
    build_as_root:
      # Configure PHP.
      # For some reason php.ini keeps being copied as a directory.
      # To fix this on rebuild where it's already happened, we need to remove the directory.
      - rm -rf /app/lando/php-conf/php.ini
      - rm -f /app/lando/php-conf/php.ini
      - cp /app/lando/php-conf/default.php.ini /app/lando/php-conf/php.ini
      # Create error logs.
      - mkdir -p /app/lando/logs
      - rm -f /app/lando/logs/php_errors.log
      - touch /app/lando/logs/php_errors.log
      - rm -f /app/lando/logs/xdebug.log
      - touch /app/lando/logs/xdebug.log
      # Install Nano for debugging purposes.
      - mkdir -p /var/lib/apt/lists/partial
      - apt-get update && apt install nano
      # Start developer out with reasonable Drupal local config.
      - cp /app/web/sites/default/default.settings.local.php /app/web/sites/default/settings.local.php
    build:
      # Custom configuration for Terminus.
      # (Terminus is installed as part of Lando Pantheon recipe).
      - mkdir -p /var/www/.terminus
      - cp /app/lando/terminus-conf/config.yml /var/www/.terminus/config.yml
    overrides:
      environment:
        # Support debugging Drush with Xdebug.
        PHP_IDE_CONFIG: "serverName=appserver"
        DRUSH_OPTIONS_URI: "https://atdove-d7.lando"
        # This is apparently necessary to overwrite the default Xdebug 3.0
        # config so that our config in /lando/php-conf/php.ini is used.
        XDEBUG_MODE:
  database:
    portforward: 32811
  mailhog:
    type: mailhog:v1.0.0
    portforward: false
    hogfrom:
      - appserver
tooling:
  # Disable pulling code via lando pull. Use git pull instead.
  pull:
    options:
      code:
        default: none
  push:
    options:
      code:
        default: none
  xdebug:
    description: Loads Xdebug in the selected mode (default mode is debug)
    cmd:
      - appserver: /app/lando/scripts/xdebug.sh
    user: root
  logs-xdebug:
    service: appserver
    description: Displays and tails Xdebug logs
    cmd: tail -f /app/lando/logs/xdebug.log
  logs-php:
    service: appserver
    description: Displays and tails PHP error logs
    cmd: tail -f /app/lando/logs/php_errors.log
  logs-drupal:
    service: appserver
    description: Tails local Drupal logs using Drush
    cmd:
      - drush en dblog -y; drush wd-show --tail --extended
  env-deploy:
    service: appserver
    description: Deploys to test or live Pantheon env (deploys code, updates database, reverts features and clears caches)
    cmd:
      - /app/lando/scripts/env-deploy.sh
  env-config-import:
    service: appserver
    description: Updates database, reverts features and clears caches on a remote Pantheon env
    cmd:
      - /app/lando/scripts/env-config-import.sh
  drupal-config-import:
    service: appserver
    description: Updates database, reverts features and clears caches on your local Lando env
    cmd:
      - /app/lando/scripts/config-import.sh
